#!/usr/bin/env bash

if [[ $(command -v stow) == "" ]]; then
        read -srn 1 -p "Do you want to install stow? (Y/n) "
        if [[ $REPLY =~ ^[Yy]$ || $REPLY == "" ]]; then
                sudo apt-get update && sudo apt-get install -y stow
        fi
fi

function emacsInstall {
        stow emacs
        curl -fsSL https://raw.githubusercontent.com/cask/cask/master/go | python
}

function bspwmInstall {
        stow bspwm
        stow sxhkd
        ln -s $HOME/.dotfiles/.xinitrc $HOME/
        ln -s $HOME/.dotfiles/.Xresources $HOME/
        ln -s $HOME/.dotfiles/flake8 $HOME/.config/
}

while getopts ":envzbh" opt; do
  case $opt in
    e)
        emacsInstall
      ;;
    n)
        stow nvim
      ;;
    v)
        stow vim
      ;;
    z)
        ln -s $HOME/.dotfiles/zsh/honukai.zsh-theme $HOME/.oh-my-zsh/themes/
      ;;
    b)
        bspwmInstall
      ;;
    h)
        echo "  -e            install emacs"
        echo "  -n            install neovim"
        echo "  -v            install vim"
        echo "  -z            install zsh-theme"
        echo "  -b            install bspwm"
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      ;;
  esac
done
