#!/bin/sh

function emacsInstall {
	stow emacs
	curl -fsSL https://raw.githubusercontent.com/cask/cask/master/go | python
}

function bspwmInstall {
	stow bspwm
	stow sxhkd
	ln -s $HOME/.dotfiles/.xinitrc $HOME/
	ln -s $HOME/.dotfiles/.Xresources $HOME/
	ln -s $HOME/.dotfiles/flake8 $HOME/.config/
}

for i in "$@"; do
	case $i in
		"-e")
			emacsInstall
		;;
		"-v")
			stow nvim
		;;
		"-z")
			ln -s $HOME/.dotfiles/zsh/honukai.zsh-theme $HOME/.oh-my-zsh/themes/
		;;
		"-b")
			bspwmInstall
		;;
		"-all")
			emacsInstall
			stow nvim
			bspwmInstall
			ln -s $HOME/.dotfiles/zsh/honukai.zsh-theme $HOME/.oh-my-zsh/themes/
		;;
		"-h")
			echo "  -e            install emacs"
			echo "  -v            install neovim"
			echo "  -z            install zsh-theme"
			echo "  -b            install bspwm"
			echo "  -all          install everything"
		;;
	esac
done
