#! /bin/sh

feh --bg-fill ~/Pictures/background/Zelda1.jpg
xsetroot -cursor_name left_ptr
amixer set Master 0

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap          12

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config presel_feedback_color \#111f35

bspc rule -a Emacs state=tiled




#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
